name: 04_excellent_go_test
on:
  pull_request:
    paths: ['go/**/*.go']
jobs:
  excellent_go_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: go test go/excellent/*.go
