name: 05_Log
on: push
jobs:
  debug-log:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::debug::This is a debug log"
  bash-tracing:
    runs-on: ubuntu-latest
    steps:
      - run: |
          set -x
          date
          hostname
