name: 05_Log
on: push
jobs:
  debug-log:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::debug::This is a debug log"
  bash-tracing:
    runs-on: ubuntu-latest
    steps:
      - run: |
          set -x
          date
          hostname
  log-group:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::group::Show environment valiables"
          printenv
          echo "::endgroup::"
  log-masked:
    runs-on: ubuntu-latest
    env:
      PASSWORD: SuperSecretValue
    steps:
      - run: echo "::add-mask::${PASSWORD}"
      - run: echo "${PASSWORD}"

